# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a Kernel matrix from a design matrix G
#' 
#' @param G A numeric matrix.
#' @return A normalized kernel matrix K.
#' @export
createK <- function(G) {
    .Call('_scMNMF_createK', PACKAGE = 'scMNMF', G)
}

